title: Grup REM
description: Grup REM — Reflexió en Educació Matemàtica
url: "https://gruprem.github.io"
baseurl: ""

theme: minima

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor

header_pages:
  - qui-som.md
  - publicacions.md
